---
title: "Statistics By States"

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: journal
runtime: shiny
---


```{r setup, include=FALSE}
library(tidyverse)
library(Rwordseg)
library(tm)
library(NLP)
library(jiebaR)
library(jiebaRD)
library(wordcloud)
library(readxl)
library(wordcloud2)
library(flexdashboard)
library(shiny)
```

```{r}
cutter = worker(stop_word = "./data/中文停用词表.txt",output = "./data")
mydata = read_excel("./data/Haircare.xlsx")
mydata_ingredient = mydata %>% 
                    select(matched_keywords)
content_ingredient = as.character(mydata_ingredient)
segwords_ingredient = segment(content_ingredient,cutter)
segwords_ingredient = subset(segwords_ingredient, nchar(as.character(segwords_ingredient))>1)
segwords_ingredient = table(segwords_ingredient)
seg_ingredient = sort(segwords_ingredient, decreasing = TRUE)
ingredient_freq = broom::tidy(segwords_ingredient)

```

Nature ingredient word cloud
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

#### Haircare

```{r}
inputPanel(
sliderInput("size", "Size", min = 1, max = 50, 
            value = 2))

```




Column 
-----------------------------------------------------------------------
  
### Wordcloud {data-height=800}
  
```{r}
renderWordcloud2({ 
wordcloud2(seg_ingredient, minRotation = -pi/2, maxRotation = -pi/2, color = "random-light", size = input$size)
})

```

### With those parameters, you can measure... {data-height=200}

```{r}

```